[project]
name = "nh-website"
version = "0.1.0"
description = "NH website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosql>=13.2",
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.34.0",
    "python-multipart>=0.0.20",
    "jinja2>=3.1.0",
    "pytest>=8.3.4",
    "selenium>=4.28.1",
    "sqlfluff>=3.3.1",
    "requests>=2.32.3",
]
[tool.pytest.ini_options]
addopts = "-vvv -rA"
testpaths = ["tests"]
